export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: "Lettuce",
    category: "seeds",
    price: 4.12,
    stock: 122,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 2,
    name: "Sunflower",
    category: "seeds",
    price: 3.02,
    stock: 147,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 3,
    name: "Tomato",
    category: "seeds",
    price: 3.63,
    stock: 90,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 4,
    name: "Lettuce",
    category: "seeds",
    price: 2.58,
    stock: 78,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 5,
    name: "Carrot",
    category: "seeds",
    price: 2.77,
    stock: 79,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 6,
    name: "Sunflower",
    category: "seeds",
    price: 4.04,
    stock: 193,
    image: "",
    tags: ["bestseller", "suggested"],
  },
  {
    id: 7,
    name: "Lettuce",
    category: "seeds",
    price: 4.3,
    stock: 56,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 8,
    name: "Lettuce",
    category: "seeds",
    price: 3.6,
    stock: 191,
    image: "",
    tags: ["bestseller", "suggested"],
  },
  {
    id: 9,
    name: "Carrot",
    category: "seeds",
    price: 4.05,
    stock: 133,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 10,
    name: "Cucumber",
    category: "seeds",
    price: 4.44,
    stock: 73,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 11,
    name: "Basil",
    category: "plants",
    price: 3.73,
    stock: 66,
    image: "",
    tags: ["bestseller", "suggested"],
  },
  {
    id: 12,
    name: "Mint",
    category: "plants",
    price: 2.95,
    stock: 185,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 13,
    name: "Rosemary",
    category: "plants",
    price: 2.08,
    stock: 91,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 14,
    name: "Thyme",
    category: "plants",
    price: 4.42,
    stock: 182,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 15,
    name: "Basil",
    category: "plants",
    price: 4.36,
    stock: 100,
    image: "",
    tags: ["suggested", "bestseller"],
  },
  {
    id: 16,
    name: "Basil",
    category: "plants",
    price: 2.73,
    stock: 87,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 17,
    name: "Mint",
    category: "plants",
    price: 3.61,
    stock: 170,
    image: "",
    tags: ["bestseller"],
  },
  {
    id: 18,
    name: "Thyme",
    category: "plants",
    price: 3.07,
    stock: 162,
    image: "",
    tags: ["bestseller"],
  },
  {
    id: 19,
    name: "Rosemary",
    category: "plants",
    price: 4.42,
    stock: 112,
    image: "",
    tags: ["suggested", "recommended"],
  },
  {
    id: 20,
    name: "Parsley",
    category: "plants",
    price: 4.47,
    stock: 131,
    image: "",
    tags: ["suggested", "bestseller"],
  },
  {
    id: 21,
    name: "Lavender",
    category: "shrubs",
    price: 2.28,
    stock: 171,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 22,
    name: "Lavender",
    category: "shrubs",
    price: 5.39,
    stock: 181,
    image: "",
    tags: ["bestseller"],
  },
  {
    id: 23,
    name: "Lavender",
    category: "shrubs",
    price: 5.06,
    stock: 91,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 24,
    name: "Hydrangea",
    category: "shrubs",
    price: 3.0,
    stock: 83,
    image: "",
    tags: ["bestseller"],
  },
  {
    id: 25,
    name: "Lavender",
    category: "shrubs",
    price: 5.49,
    stock: 169,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 26,
    name: "Camellia",
    category: "shrubs",
    price: 3.48,
    stock: 142,
    image: "",
    tags: ["bestseller"],
  },
  {
    id: 27,
    name: "Azalea",
    category: "shrubs",
    price: 2.29,
    stock: 179,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 28,
    name: "Forsythia",
    category: "shrubs",
    price: 3.63,
    stock: 109,
    image: "",
    tags: ["recommended", "bestseller"],
  },
  {
    id: 29,
    name: "Azalea",
    category: "shrubs",
    price: 2.8,
    stock: 73,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 30,
    name: "Lavender",
    category: "shrubs",
    price: 4.57,
    stock: 159,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 31,
    name: "Lily",
    category: "bulbs",
    price: 3.93,
    stock: 100,
    image: "",
    tags: ["suggested", "bestseller"],
  },
  {
    id: 32,
    name: "Daffodil",
    category: "bulbs",
    price: 2.79,
    stock: 70,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 33,
    name: "Crocus",
    category: "bulbs",
    price: 4.43,
    stock: 130,
    image: "",
    tags: ["bestseller"],
  },
  {
    id: 34,
    name: "Lily",
    category: "bulbs",
    price: 4.8,
    stock: 177,
    image: "",
    tags: ["bestseller", "suggested"],
  },
  {
    id: 35,
    name: "Crocus",
    category: "bulbs",
    price: 4.25,
    stock: 85,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 36,
    name: "Daffodil",
    category: "bulbs",
    price: 4.79,
    stock: 112,
    image: "",
    tags: ["suggested", "bestseller"],
  },
  {
    id: 37,
    name: "Lily",
    category: "bulbs",
    price: 3.96,
    stock: 135,
    image: "",
    tags: ["suggested", "recommended"],
  },
  {
    id: 38,
    name: "Tulip",
    category: "bulbs",
    price: 3.57,
    stock: 61,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 39,
    name: "Lily",
    category: "bulbs",
    price: 5.39,
    stock: 66,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 40,
    name: "Tulip",
    category: "bulbs",
    price: 4.09,
    stock: 58,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 41,
    name: "Fennel",
    category: "roots",
    price: 4.49,
    stock: 165,
    image: "",
    tags: ["suggested", "bestseller"],
  },
  {
    id: 42,
    name: "Fennel",
    category: "roots",
    price: 2.21,
    stock: 151,
    image: "",
    tags: ["bestseller", "recommended"],
  },
  {
    id: 43,
    name: "Hosta",
    category: "roots",
    price: 3.76,
    stock: 71,
    image: "",
    tags: ["bestseller", "recommended"],
  },
  {
    id: 44,
    name: "Hosta",
    category: "roots",
    price: 3.6,
    stock: 196,
    image: "",
    tags: ["recommended", "bestseller"],
  },
  {
    id: 45,
    name: "Hosta",
    category: "roots",
    price: 4.2,
    stock: 69,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 46,
    name: "Fennel",
    category: "roots",
    price: 3.35,
    stock: 146,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 47,
    name: "Astilbe",
    category: "roots",
    price: 4.89,
    stock: 143,
    image: "",
    tags: ["recommended"],
  },
  {
    id: 48,
    name: "Fennel",
    category: "roots",
    price: 2.37,
    stock: 156,
    image: "",
    tags: ["recommended", "suggested"],
  },
  {
    id: 49,
    name: "Fennel",
    category: "roots",
    price: 3.38,
    stock: 124,
    image: "",
    tags: ["suggested"],
  },
  {
    id: 50,
    name: "Peony",
    category: "roots",
    price: 2.99,
    stock: 127,
    image: "",
    tags: ["suggested", "recommended"],
  },
];
